//go:build wasm

// web/client.go — WebAssembly entry point for this module.
// Generated by webtyp (https://pkg.go.dev/webtyp.com/app) when this file does not
// exist, copied from webtyp.com/html/scaffold at the version installed in go.mod.
//
// DOM access:           webtyp.com/dom  — https://pkg.go.dev/webtyp.com/dom
// Element constructors: webtyp.com/html — https://pkg.go.dev/webtyp.com/html
// Do NOT use syscall/js directly; webtyp/dom wraps it with a typed builder API.
//
// In WASM files never import the Go stdlib; use the webtyp replacements:
//   fmt, errors, strconv, strings → webtyp.com/fmt
//   encoding/json                 → webtyp.com/json
//   time                          → webtyp.com/time
//   net/http                      → webtyp.com/fetch

package main

import (
	. "webtyp.com/dom"
	. "webtyp.com/fmt"
	. "webtyp.com/html"
)

// App holds application state. Embed Element as a value (never pointer) to
// minimize heap allocations in TinyGo's GC.
type App struct {
	Element
	clicks int
	count  *SignalString
}

func (a *App) Init(_ Ctx) {
	a.count = NewString("0")
}

func (a *App) Render() *Element {
	return Div().Child(
		H1().Text("Hello from webtyp!"),
		Button().Text("Click me").Class("btn").OnClick(func(e Event) {
			a.clicks++
			a.count.Set(Sprint(a.clicks)) // signal update patches only the text node
		}),
		P().Child(
			NewElement("span").Text("Clicks: "),
			NewElement("span").BindText(a.count),
		),
	)
}

func main() {
	// Inline CSS is fine for prototyping. A real component declares its styles in
	// css.go with webtyp.com/widget/style — see https://pkg.go.dev/webtyp.com/components
	Append("head", Style().Text(`
		.btn { padding: .4rem 1rem; cursor: pointer; border: none; border-radius: 4px; background: #007bff; color: white; }
	`))

	Render("app", &App{})

	// select{} keeps the WASM goroutine alive so JS event callbacks keep working.
	select {}
}
